### ISSUE TITLE
v2 contains avoidable failure cases

### ISSUE THREAD

**Issue by jcogilvie** [traefik/traefikee-helm-chart#101]
First, let me say the v2 chart is a welcome upgrade.  Almost everything included is a big win.

That said, there are two avoidable failure cases.

Let me preface this by saying my terraform infra first runs a call to `helm template` before anything gets applied, in order to diff the chart between last version and this version.

So, the first avoidable failure case is the call to `fail` in `NOTES.txt`.  Two cases this can happen in:

* I may be trying to deploy the external configmap + the helm release atomically, in which case the configmap does not exist until the entire change set is complete (and terraform handles the dependency ordering for me)
* I may not have local access to the cluster when running `helm template` so the lookup will fail

Recommendation:  don't `fail`; just print a warning in the notes.

Second case:  for the static config, specifying the external configMap conflicts with the `contents` field (breaking backwards compatibility).  In my opinion, the external configmap should supersede the `contents` field if specified.  This avoids failure while retaining backwards compatibility with old versions.

Or if you prefer, you could add a flag:

```yaml
staticConfig:
  configMap:
    enabled: true # default false
```

It still provided a defined behavior for the case of a conflict, even if not backwards compatible.

**Comment by darkweaver87** [comment]
Many thanks for your feedback.

I would advocate pro the `fail` because I usually prefer something which crashes when there is an issue rather than failing silently.
If you install your helm release through a CD tool (fluxcd, argocd, ...) you won't see notes but you will see reconciliation failure.

To address your concerns about configmap what do you think adding a flag like:
```yaml
  staticConfig:         
    configMap:          
      name: traefik-conf
      key: "static.yml" 
      ignoreFailedLookup: false
```

For your other concern, we thought about adding the `content` field by default because we don't know what users are specifying in their config but we need for it to work on a clean install at least to enable `ping` feature. But it makes sense to just rely on the test done against the inline config or the configmap and just warn the user its inline config will be ignored as a config map is specified. I'll do a PR for this.

**Comment by mloiseleur** [comment]
@jcogilvie The code has been reworked with #103. It's now only a warning and the consistency check between configmap content and spec template is now applied on both sources. 

Feel free to re-open if we missed something.
